version: "3.9"
services:

  tomcat:
    init: true
    hostname: tomcat
    container_name: tomcat
    image: tomcat:9.0
    ports:
      - "${TOMCAT_PORT}:8080"
    volumes:
      - ./intentional/build/libs/:/usr/local/tomcat/webapps/

  lamp:
    init: true
    hostname: lamp
    container_name: lamp
    image: mattrayner/lamp:latest-1804
    ports:
      - "${LAMP_PORT}:80"
    volumes:
      - ./web:/var/www/html

  oracledb:
    init: true
    hostname: oracledb
    container_name: oracledb
    build: intentional/dockerimages/oracle11g
    environment:
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ALLOW_REMOTE=true
    ports:
      - "${ORACLE_PORT}:${ORACLE_PORT}"
      - 5500:5500
    volumes:
      - ./intentional/resources/:/data
